[package]
name = "rust-proj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

mongodb = "2.8.2"

tokio = {version = "1.36.0", features = ["full"]}

serde = "1.0.197"

serde_json = "1.0.114"